apiVersion: v2
name: flask-app-config
description: Configuração GitOps para a API Flask
version: 1.0.0

dependencies:
  - name: helm-base-k8s-app
    version: "0.1.0"
    repository: "https://github.com/wesleysouza/helm-charts"