apiVersion: v2
name: flask-app-config
description: Configuração GitOps para a API Flask
version: 1.2.9

dependencies:
  - name: argorollouts-k8s-app
    version: "0.0.4"
    repository: "https://wesleysouza.github.io/helm-charts/"