apiVersion: v2
name: flask-app-config
description: Configuração GitOps para a API Flask
version: 1.0.1

dependencies:
  - name: base-k8s-app
    version: "0.1.1"
    repository: "https://wesleysouza.github.io/helm-charts/"