base-k8s-app:
  replicaCount: 3

  image:
    repository: nginx
    # Esta tag será a única coisa alterada pelo seu pipeline de CI no outro repositório
    tag: "stable"
  
  service:
    port: 80
    targetPort: 80

  ingress:
    enabled: true
    className: "nginx"
    hosts:
      - host: api.flaskapp.com.br
        paths:
          - path: /
            pathType: Prefix

  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "300m"
      memory: "256Mi"

  env:
    - name: FLASK_ENV
      value: "production"
    - name: WORKERS
      value: "4"

  livenessProbe:
    enabled: true
    path: /
    port: 80
  readinessProbe:
    enabled: true
    path: /
    port: 80