replicaCount: 3

image:
  repository: nginxinc/nginx-unprivileged
  tag: 1.25-alpine

service:
  type: ClusterIP
  port: 80

ingress:
  host: app.exemplo.com
  annotations:
    kubernetes.io/ingress.class: nginx

rollout:
  steps:
    - setWeight: 20
    - pause: {} # Pausa manual
    - setWeight: 50
    - pause: {} # Pausa manual
    - setWeight: 100